movie_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movies.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.MoviesView.as_view()),
    path('<slug:slug>/', views.MovieDetailView.as_view(), name='movie_detail'),
    path('review/<int:pk>/', views.AddReview.as_view(), name='add_review'),
]

movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Category(BaseModel):
    """Categories model for db"""
    name = models.CharField('Category', max_length=150)
    description = models.TextField('Description')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Actor(BaseModel):
    """Actors model for db"""
    name = models.CharField('Actor', max_length=150)
    description = models.TextField('Description')
    age = models.PositiveSmallIntegerField('Age', default=0)
    image = models.ImageField('Image', upload_to='actors/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Actors & Directors'
        verbose_name_plural = 'Actors & Directors'


class Genre(BaseModel):
    """Genre model for db"""
    name = models.CharField('Genre', max_length=150)
    description = models.TextField('Description')
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Genre'
        verbose_name_plural = 'Genres'


class Movie(BaseModel):
    """Movie model for db"""
    title = models.CharField('Title', max_length=100)
    tag = models.CharField('Tagline', max_length=100, default='')
    description = models.TextField('Description')
    poster = models.ImageField('Poster', upload_to='movies/')
    year = models.PositiveSmallIntegerField('Release date', default=date.today)
    country = models.CharField('Country', max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name='Director',
                                       related_name='film_director')
    actors = models.ManyToManyField(Actor, verbose_name='Actors',
                                    related_name='film_actors')
    genres = models.ManyToManyField(Genre, verbose_name='Genres')
    world_premiere = models.DateField('World premiere date',
                                      default=date.today)
    budget = models.PositiveIntegerField('Budget', default=0,
                                         help_text='Specify the amount in dollars')
    fees_in_Russia = models.PositiveIntegerField(
        'Fees in Russia', default=0, help_text='Specify the amount in dollars')
    fees_in_world = models.PositiveIntegerField(
        'Fees in World', default=0, help_text='Specify the amount in dollars')
    category = models.ForeignKey(
        Category, verbose_name='Category', on_delete=models.SET_NULL, null=True)
    url = models.SlugField(max_length=160, unique=True)
    draft = models.BooleanField('Draft', default=False)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('movie_detail', kwargs={'slug': self.url})

    class Meta:
        verbose_name = 'Movie'
        verbose_name_plural = 'Movies'


class MovieShots(BaseModel):
    """Movie shots model for db"""
    title = models.CharField('Title', max_length=100)
    description = models.TextField('Description')
    image = models.ImageField('Image', upload_to='movie_shots/')
    movie = models.ForeignKey(Movie, verbose_name='Film',
                              on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Movie shot'
        verbose_name_plural = 'Movie shots'


class RatingStar(BaseModel):
    """Rating star model for db"""
    value = models.PositiveSmallIntegerField('Value', default=0)

    def __str__(self):
        return self.value

    class Meta:
        verbose_name = 'Rating star'
        verbose_name_plural = 'Rating stars'


class Rating(BaseModel):
    """Rating model for db"""
    user_ip = models.CharField('User IP', max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE,
                             verbose_name='Star')
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE,
                              verbose_name='Film')

    def __str__(self):
        return f'{self.star} - {self.movie}'

    class Meta:
        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'


class Reviews(BaseModel):
    """Reviews model for db"""
    email = models.EmailField()
    name = models.CharField('User name', max_length=100)
    text = models.TextField('Review', max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name='Parent', on_delete=models.SET_NULL,
        blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name='Film',
                              on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} - {self.movie}'

    class Meta:
        verbose_name = 'Review'
        verbose_name_plural = 'Reviews'

movies/forms.py
from django import forms
from .models import Reviews


class ReviewForm(forms.ModelForm):
    """Collecting client data from comment form"""
    class Meta:
        model = Reviews
        fields = ('name', 'email', 'text')

movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from django.views.generic.base import View
from django.views.generic import ListView, DetailView
from .forms import ReviewForm


class MoviesView(View):
    """Movies list"""

    # model = Movie
    # queryset = Movie.objects.filter(draft=False)

    def get(self, request):
        movies = Movie.objects.all()
        return render(request, 'movies/movie_list.html', {'movies_list': movies})


class MovieDetailView(DetailView):
    """Full description of the film"""

    model = Movie
    slug_field = 'url'

    # def get(self, request, slug):
    #     movie = Movie.objects.get(url=slug)
    #     return render(request, "movie/movie_detail.html", {'movie': movie})


class AddReview(View):
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        movie = Movie.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.movie = movie
            form.save()
        return redirect(movie.get_absolute_url())

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <title>{% block title %}  {% endblock title %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{%  static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{%  static 'css/style.css' %}" type="text/css" media="all">
        <link rel="stylesheet" href="{%  static 'css/font-awesome.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700"
              rel="stylesheet">
        <link href="//fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900"
              rel="stylesheet">
    </head>
    <body>
        <div id="page" class="page">
            <div class="main-banner bg {% block header %}  {% endblock header %}" id="home">
                {% include 'include/header.html' %}
            </div>
            <ol class="breadcrumb editContent">
                <li class="breadcrumb-item">
                    <a href="index.html" class="editContent">Home</a>
                </li>
                <li class="breadcrumb-item active editContent">Single Page</li>
            </ol>
            {% block content %}

            {% endblock content %}
        {% include 'include/footer.html' %}
        </div>
    </body>
</html>

templates/include/header.html
<header class="header">
    <div class="container-fluid px-lg-5">
        <!-- nav -->
        <nav class="py-4">
            <div id="logo">
                <h1> <a href="index.html" class="editContent" style="outline: none; outline-offset: -2px; cursor: inherit; color: rgb(255, 255, 255); font-size: 40px; background-color: rgba(0, 0, 0, 0); font-family: &quot;Source Sans Pro&quot;, sans-serif;">DjangoMovie</a></h1>
            </div>

            <label for="drop" class="toggle">Menu</label>
            <input type="checkbox" id="drop">
            <ul class="menu mt-2">
                <li class="active"><a href="index.html">Главная</a></li>
                <li>
                    <!-- First Tier Drop Down -->
                    <label for="drop-2" class="toggle">Categories<span class="fa fa-angle-down" aria-hidden="true" ></span> </label>
                    <a href="#">Categories<span class="fa fa-angle-down" aria-hidden="true"></span></a>
                    <input type="checkbox" id="drop-2">
                    <ul>
                        <li><a href="moviesingle.html">Фильмы</a></li>
                        <li><a href="moviesingle.html">Сериалы</a></li>
                        <li><a href="moviesingle.html">Мультфильмы</a></li>
                    </ul>
                </li>
                <li><a href="contact.html" style="color: rgb(255, 255, 255); font-weight: 700; text-transform: uppercase;">Вход</a></li>
            </ul>
        </nav>
        <!-- //nav -->
    </div>
</header>
    <!-- //header -->
    <!--/banner-->
    <div class="banner-info">
        <p class="editContent" >лучший сайт на django 3</p>
        <h3 class="mb-4 editContent">Все о кино</h3>
        <div class="ban-buttons">


        </div>
    </div>

templates/movie/movie_detail.html
{% extends 'movie/base.html' %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6">
            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.title }}
            </h3>
            <ul>
                <li style="list-style: none"><span><b>Year:</b> {{ movie.year }}</span></li>
                <li style="list-style: none"><span><b>Country:</b> {{ movie.country }}</span>
                </li>
                <li style="list-style: none"><span><b>Tagline:</b> {{ movie.tag }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Directors:</b>
                        {% for director in movie.directors.all %}
                            {{ director.name }}
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none">
                    <span><b>Actors:</b>
                        {% for actor in movie.actors.all %}
                            {{ actor.name }}
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none"><span><b>Genre:</b>
                    {% for genre in movie.genres.all %}
                            {{ genre }}
                        {% endfor %}
                </span>
                </li>
                <li style="list-style: none"><span><b>World premier:</b>{{ movie.world_premiere }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Budget:</b>${{ movie.budget }}</span></li>
                <li style="list-style: none">
                    <span><b>Fees in Russia:</b>{{ movie.fees_in_Russia }}</span></li>
                <li style="list-style: none"><span><b>Fees in World:</b>${{ movie.fees_in_world }}</span>
                </li>
                <li style="list-style: none">
                    <a href="#"><b>Rating:</b>
                    <span class="fa fa-star" aria-hidden="true"
                          style="outline: none; cursor: inherit;"></span>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                        <span class="editContent"
                              style="outline: none; cursor: inherit;">5.0</span>
                    </a>
                </li>
                <div class="share-desc">
                    <div class="share">
                        <h4 class="editContent"
                            style="outline: none; cursor: inherit;">
                            Share:</h4>
                        <ul class="w3layouts_social_list list-unstyled">
                            <li>
                                <a href="#" class="w3pvt_facebook editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-facebook-f"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_twitter editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-twitter"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="w3pvt_dribble editContent"
                                   style="outline: none; cursor: inherit;">
                                <span class="fa fa-dribbble"
                                      style="outline: none; cursor: inherit;"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </ul>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            About film {{ movie.title }}</h3>
        <p>
            {%  for image in movie.movieshots_set.all %}
                <img src="{{ image.image.url }}"  class="img-movie-shots" alt="{{ image.description }}">
            {% endfor %}
        </p>
        <p class="editContent" style="outline: none; cursor: inherit;">
            {{ movie.description }}
        </p>
        <p class="mt-3 italic-blue editContent"
           style="outline: none; cursor: inherit;">
            <iframe width="560" height="315"
                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                    frameborder="0" allow="accelerometer; autoplay;
                                                           encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen>

            </iframe>
        </p>
    </div>
    <hr>
    <div class="row">
        <div class="single-form-left">
            <!-- contact form grid -->
            <div class="contact-single">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    <span class="sub-tittle editContent"
                          style="outline: none; cursor: inherit;">02</span>Оставить отзыв</h3>
                <form action="#" method="get" class="mt-4">
                    <div class="form-group editContent"
                         style="outline: none; cursor: inherit;">
                        <label for="contactcomment" class="editContent"
                               style="outline: none; cursor: inherit;">Ваш комментарий
                            *</label>
                        <textarea class="form-control border" rows="5"
                                  id="contactcomment" required=""></textarea>
                    </div>
                    <div class="d-sm-flex">
                        <div class="col-sm-6 form-group p-0 editContent"
                             style="outline: none; cursor: inherit;">
                            <label for="contactusername" class="editContent"
                                   style="outline: none; cursor: inherit;">Имя
                                *</label>
                            <input type="text" class="form-control border"
                                   id="contactusername" required="">
                        </div>
                        <div class="col-sm-6 form-group ml-sm-3 editContent"
                             style="outline: none; cursor: inherit;">
                            <label for="contactemail" class="editContent"
                                   style="outline: none; cursor: inherit;">Email
                                *</label>
                            <input type="email" class="form-control border"
                                   id="contactemail" required="">
                        </div>
                    </div>
                    <button type="submit"
                            class="mt-3 btn btn-success btn-block py-3"
                            style="outline: none; cursor: inherit;">Отправить
                    </button>
                </form>
            </div>
            <!--  //contact form grid ends here -->
        </div>
        <div class="media py-5">
            <img src="bundles/images/te2.jpg" class="mr-3 img-fluid" alt="image"
                 style="outline: none; cursor: inherit;">
            <div class="media-body mt-4">
                <h5 class="mt-0 editContent"
                    style="outline: none; cursor: inherit;">Daniel Doe</h5>
                <p class="mt-2 editContent" style="outline: none; cursor: inherit;">
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus
                    scelerisque ante sollicitudin. Cras purus odio, vestibulum in
                    vulputate at, tempus viverra turpis.
                </p>
                <div class="media mt-5 editContent"
                     style="outline: none; cursor: inherit;">
                    <a class="pr-3" href="#">
                        <img src="bundles/images/te1.jpg" class="img-fluid "
                             alt="image" style="outline: none; cursor: inherit;">
                    </a>
                    <div class="media-body">
                        <h5 class="mt-0 editContent"
                            style="outline: none; cursor: inherit;">Leia Organa</h5>
                        <p class="mt-2 editContent"
                           style="outline: none; cursor: inherit;"> Cras sit amet
                            nibh libero, in gravida nulla. Nulla vel metus
                            scelerisque ante sollicitudin. Cras purus odio,
                            vestibulum in vulputate at, tempus viverra turpis. Fusce
                            condimentum nunc ac nisi vulputate fringilla..</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock movie %}

templates/movies/base.html
{% extends 'base.html' %}
{% block content %}
<section class="ab-info-main py-md-5 py-4 editContent"
         style="padding-left: 3rem; padding-right: 3rem;">
    {% block container %}
        <div class="container-fluid py-md-3">
    {% endblock container %}
        <div class="row">
        {% block sidebar %}
            <div class="side-bar col-lg-3">
        {% endblock sidebar %}
                {% include 'include/sidebar.html' %}
            </div>
        {% block movie %}
        {%  endblock movie %}
        </div>
    </div>
</section>
{% endblock content %}

templates/movies/movie_detail.html
{% extends 'movies/base.html' %}
{% block title %} {{ movie.title }} {% endblock title %}
{% block container %}
    <div class="container py-md-3">
{% endblock container %}

{% block sidebar %}
    <div class="side-bar col-lg-4">
{% endblock sidebar %}

{% block movie %}
<div class="left-ads-display col-lg-8">
    <div class="row">
        <div class="desc1-left col-md-6">
            <img src="{{ movie.poster.url }}" class="img-fluid" alt="">
        </div>
        <div class="desc1-right col-md-6 pl-lg-4">
            <h3 class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.title }}
            </h3>
            <ul>
                <li style="list-style: none"><span><b>Year:</b> {{ movie.year }}</span></li>
                <li style="list-style: none"><span><b>Country:</b> {{ movie.country }}</span>
                </li>
                <li style="list-style: none"><span><b>Tagline:</b> {{ movie.tag }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Directors:</b>
                        {% for director in movie.directors.all %}
                            {{ director.name }}
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none">
                    <span><b>Actors:</b>
                        {% for actor in movie.actors.all %}
                            {{ actor.name }}
                        {% endfor %}
                    </span>
                </li>
                <li style="list-style: none"><span><b>Genre:</b>
                    {% for genre in movie.genres.all %}
                            {{ genre }}
                        {% endfor %}
                </span>
                </li>
                <li style="list-style: none"><span><b>World premier:</b>{{ movie.world_premiere }}</span>
                </li>
                <li style="list-style: none">
                    <span><b>Budget:</b>${{ movie.budget }}</span></li>
                <li style="list-style: none">
                    <span><b>Fees in Russia:</b>{{ movie.fees_in_Russia }}</span></li>
                <li style="list-style: none"><span><b>Fees in World:</b>${{ movie.fees_in_world }}</span>
                </li>
                <li style="list-style: none">
                    <a href="#"><b>Rating:</b>
                    <span class="fa fa-star" aria-hidden="true"
                          style="outline: none; cursor: inherit;"></span>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                        <span class="fa fa-star" aria-hidden="true"
                              style="outline: none; cursor: inherit;"></span>
                        <span class="editContent"
                              style="outline: none; cursor: inherit;">5.0</span>
                    </a>
                </li>
            </ul>
            <div class="share-desc">
                <div class="share">
                    <h4 class="editContent"
                        style="outline: none; cursor: inherit;">
                        Share:</h4>
                    <ul class="w3layouts_social_list list-unstyled">
                        <li>
                            <a href="#" class="w3pvt_facebook editContent"
                               style="outline: none; cursor: inherit;">
                            <span class="fa fa-facebook-f"
                                  style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="w3pvt_twitter editContent"
                               style="outline: none; cursor: inherit;">
                            <span class="fa fa-twitter"
                                  style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                        <li>
                            <a href="#" class="w3pvt_dribble editContent"
                               style="outline: none; cursor: inherit;">
                            <span class="fa fa-dribbble"
                                  style="outline: none; cursor: inherit;"></span>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row sub-para-w3layouts mt-5">
        <h3 class="shop-sing editContent" style="outline: none; cursor: inherit;">
            About film {{ movie.title }}</h3>
            <div>
                {%  for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}"  class="img-movie-shots" alt="{{ image.description }}" style="max-width: 250px; height: auto;">
                {% endfor %}
            </div>
        <p class="editContent" style="outline: none; cursor: inherit;">
            {{ movie.description }}
        </p>
        <p class="mt-3 italic-blue editContent"
           style="outline: none; cursor: inherit;">
            <iframe width="560" height="315"
                    src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                    frameborder="0" allow="accelerometer; autoplay;
                                                           encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen>

            </iframe>
        </p>
    </div>
    <hr>
    <div class="row">
        <div class="single-form-left">
            <!-- contact form grid -->
            <div class="contact-single">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    <span class="sub-tittle editContent"
                          style="outline: none; cursor: inherit;">02</span>Post a comment</h3>
                <form action="{% url 'add_review'  movie.id %}" method="post" class="mt-4">
                    {% csrf_token %}
                    <div class="form-group editContent">
                        <label for="contactcomment" class="editContent">
                            Your comment *
                        </label>
                        <textarea class="form-control border" rows="5"
                                  name="text"
                                  id="contactcomment" required=""></textarea>
                    </div>
                    <div class="d-sm-flex">
                        <div class="col-sm-6 form-group p-0 editContent">
                            <label for="contactusername" class="editContent">
                                Name *
                            </label>
                            <input type="text" class="form-control border"
                                   name="name"
                                   id="contactusername" required="">
                        </div>
                        <div class="col-sm-6 form-group ml-sm-3 editContent">
                            <label for="contactemail" class="editContent">
                                Email *
                            </label>
                            <input type="email" class="form-control border"
                                   name="email"
                                   id="contactemail" required="">
                        </div>
                    </div>
                    <button type="submit"
                            class="mt-3 btn btn-success btn-block py-3">
                        Send
                    </button>
                </form>
            </div>
        </div>
        {% for review in movie.reviews_set.all %}
            <div class="media py-5">
                <img src="bundles/images/te2.jpg" class="mr-3 img-fluid" alt="image">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ review.name }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ review.text }}
                    </p>
    {#                <div class="media mt-5 editContent"#}
    {#                     style="outline: none; cursor: inherit;">#}
    {#                    <a class="pr-3" href="#">#}
    {#                        <img src="bundles/images/te1.jpg" class="img-fluid "#}
    {#                             alt="image" style="outline: none; cursor: inherit;">#}
    {#                    </a>#}
    {#                    <div class="media-body">#}
    {#                        <h5 class="mt-0 editContent"#}
    {#                            style="outline: none; cursor: inherit;">Leia Organa</h5>#}
    {#                        <p class="mt-2 editContent"#}
    {#                           style="outline: none; cursor: inherit;"> Cras sit amet#}
    {#                            nibh libero, in gravida nulla. Nulla vel metus#}
    {#                            scelerisque ante sollicitudin. Cras purus odio,#}
    {#                            vestibulum in vulputate at, tempus viverra turpis. Fusce#}
    {#                            condimentum nunc ac nisi vulputate fringilla..</p>#}
    {#                    </div>#}
    {#                </div>#}
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock movie %}